
import "./globals.css";

export const metadata = {
  title: "Minutes of meeting",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
export default RootLayout
